version: 2.1
commands:
  runtests:
    steps:
      - checkout
      - restore_cache: # Download and cache dependencies
          key: libhoney-java-{{ checksum "pom.xml" }}-<< parameters.javaversion >>
      - run: ./mvnw dependency:go-offline # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: libhoney-java-{{ checksum "pom.xml" }}-<< parameters.javaversion >>
      - run: ./mvnw package # run the actual tests
executors:
  java:
    parameters:
      javaversion:
        type: string
        default: "8"
    working_directory: ~/libhoney-java
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    docker:
      - image: circleci/openjdk:<<parameters.javaversion>>-jdk
#  java9:
#    working_directory: ~/libhoney-java
#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#    docker:
#      - image: circleci/openjdk:9-jdk-sid
#  java10:
#    working_directory: ~/libhoney-java
#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#    docker:
#      - image: circleci/openjdk:10-jdk-sid
#  java11:
#    working_directory: ~/libhoney-java
#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#    docker:
#      - image: circleci/openjdk:11-jdk-stretch
jobs:
  java8:
    parameters:
      javaversion:
        type: string
        default: "8"
    executor:
      name: java
      javaversion: "<< parameters.javaversion >>"
    steps:
      - runtests
#  java9:
#    executor: java9
#    steps:
#      - runtests
#  java10:
#    executor: java10
#    steps:
#      - runtests
#  java11:
#    executor: java11
#    steps:
#      - runtests
workflows:
  version: 2
  build:
    jobs:
      - java8:
          - javaversion: "8"
#      - java9
#      - java10
#      - java11
